<?php
    print("{");
    print("\"catalog\" : { ");
    print("\"song\" : [ ");
    print("{");
    print("\"title\" : \"I Want to Know What Love Is\" ," );
    print("\"artist\" : \"Foreigner\" ," );
    print("\"rating\" : \"10\" ");
    print("},");
    print("{");
    print("\"title\" : \"Tragedy\" ," );
    print("\"artist\" : \"Bee Gees\" ," );
    print("\"rating\" : \"6\" ");
    print("},");
    print("{");
    print("\"title\" : \"They Dance Alone\" ," );
    print("\"artist\" : \"Sting\" ," );
    print("\"rating\" : \"10\" ");
    print("},");
    print("{");
    print("\"title\" : \"Biko\" ," );
    print("\"artist\" : \"Peter Gabriel\" ," );
    print("\"rating\" : \"10\" ");
    print("},");
    print("{");
    print("\"title\" : \"Keep On Loving You\" ," );
    print("\"artist\" : \"REO Speedwagon\" ," );
    print("\"rating\" : \"9\" ");
    print("},");
    print("{");
    print("\"title\" : \"Sailing\" ," );
    print("\"artist\" : \"Christopher Cross\" ," );
    print("\"rating\" : \"9\" ");
    print("},");
    print("{");
    print("\"title\" : \"Beat It\" ," );
    print("\"artist\" : \"Michael Jackson\" ," );
    print("\"rating\" : \"7\" ");
    print("}");
    print("]");
    print("}");
    print("}");
?>